host_password: "Geschichteistmachbar!"

# Pretalx-Section
pretalx:
  json_url: 'https://programm.infraunited.org/scc-25-2025/schedule/export/schedule.json' # Schedule in JSON-Format
  cache_time: 60 # Caches data from schedule for X minutes

# FastAPI-Section
fastapi:
  host: 127.0.0.1 #Host to bind FastAPI server
  port: 8000 # Port to bind FastAPI server

# Whisper-Section
whisper:
  langs:
    - de
    - en
  max_instances: 2
  close_room_after_seconds: 10 # TODO: revert to 300s (5m) for production

# LibreTranslate-Section
libretranslate:
  host: 127.0.0.1 # Host to bind LibreTranslate server
  port: 5000 # Port to bind LibreTranslate server
  langs: 'https://libretranslate.com/languages'

# Data-Section
data:
  transcript_db_directory: 'transcripts_db'
