host_password: "Geschichteistmachbar!"
admin_password: "Wasistesdiesmal?"

# Pretalx-Section
pretalx:
  json_url: 'https://programm.infraunited.org/scc-25-2025/schedule/export/schedule.json' # Schedule in JSON-Format
  cache_time: 60 # Caches data from schedule for X minutes
  # The names of the Tracks that shall not be shown - Leave empty {} to use all tracks - has to be the exact writing!
  filter_tracks: !!set {"blockiert", "Anderes Format", "Vernetzungs oder Strategieraum", "Performance, Konzert", "Austauschrunde"}
  # fake_now: '2025-08-20T16:00:00+02:00' # Has to be an ISO-8601 datetime string or empty

# FastAPI-Section
fastapi:
  host: 0.0.0.0 #Host to bind FastAPI server
  port: 8000 # Port to bind FastAPI server

# Whisper-Section
whisper:
  langs:
    - en
    - de
    - es
    - fr
    - it
    - ja
    - pt
    - ru
    - nl
    - ko
    - uk
  max_instances: 2
  close_room_after_seconds: 10 # TODO: revert to 300s (5m) for production

# LibreTranslate-Section
libretranslate:
  host: 127.0.0.1 # Host to bind LibreTranslate server
  port: 5000 # Port to bind LibreTranslate server
  langs: 'https://libretranslate.com/languages'

# Data-Section
data:
  transcript_db_directory: 'transcripts_db'
  votes_directory: 'votes'
