services:
  whisper-server:
    build: .
    ports:
      - "8000:8000"
      - "5000:5000"
      - "5000:5000"
    volumes:
      - ./src:/app/src:z  # Mount src for live code updates
    command: >
      poetry run python src/whisper_server.py
      --model tiny
      --libretranslate-url 127.0.0.1
      --libretranslate-port 5000
      --source-lang de
      --target-lang en
      --timeout 4